import type { CuratedPromoDiscoveryRow } from '../mappers/curatedPromoDiscoveryMapper'

/** View-shaped rows for mocks and mapper tests (v_curated_promo_discovery). */
export const curatedPromoDiscoveryViewRows: CuratedPromoDiscoveryRow[] = [
  {
    promo_id: 'mock-promo-venetian-freeplay',
    promo_slug: 'venetian-las-vegas-freeplay-mar-2026',
    brand: 'Venetian',
    market_slug: 'las-vegas',
    location_label: 'Las Vegas',
    title: 'Spring free play bundle',
    subtitle: 'Tracked from property website',
    source_kind: 'website',
    source_url: 'https://example.com/venetian-promo',
    primary_asset_url: null,
    active_status: 'active',
    visible_start_date: '2026-03-01',
    visible_end_date: '2026-03-31',
    observed_at: '2026-03-15T12:00:00.000Z',
    signal_families: ['freeplay'],
    signal_types: ['match_play', 'bonus_spin'],
    gameplay_tags: [],
    badges: ['source-backed'],
    signals_json: [
      {
        signal_id: 'mock-promo-venetian-freeplay:v0:0:offer_details.match_play',
        signal_type: 'match_play',
        signal_family: 'freeplay',
        label: 'Match play',
        value_raw: '$50 match play',
        value_normalized: '$50',
        confidence: 0.92,
        evidence_text: 'Match play listed on promo page.',
        extraction_key: 'offer_details.match_play',
      },
      {
        signal_id: 'mock-promo-venetian-freeplay:v0:1:offer_details.bonus_spin',
        signal_type: 'bonus_spin',
        signal_family: 'freeplay',
        label: 'Bonus spins',
        value_raw: '25 bonus spins',
        value_normalized: '25 spins',
        confidence: '0.88',
        evidence_text: null,
        extraction_key: 'offer_details.bonus_spin',
      },
    ],
    top_signals_json: [
      {
        signal_id: 'mock-promo-venetian-freeplay:v0:0:offer_details.match_play',
        signal_type: 'match_play',
        signal_family: 'freeplay',
        label: 'Match play',
        value_raw: '$50 match play',
        value_normalized: '$50',
        confidence: 0.92,
        extraction_key: 'offer_details.match_play',
      },
    ],
    evidence_json: [
      {
        evidence_type: 'text',
        label: 'Promo page capture',
        text: 'Enjoy a $75 Daily Dining Credit for each night stayed.',
        extraction_key: 'offer_details.dining_credit',
        confidence: '0.95',
      },
    ],
  },
  {
    promo_id: 'mock-promo-manual-capture',
    promo_slug: 'aria-manual-capture',
    brand: 'Aria',
    market_slug: 'las-vegas',
    location_label: 'Las Vegas',
    title: 'Manual host offer note',
    subtitle: 'Captured without outbound URL',
    source_kind: 'manual',
    source_url: null,
    primary_asset_url: null,
    active_status: 'unknown',
    visible_start_date: null,
    visible_end_date: null,
    observed_at: '2026-03-10T09:30:00.000Z',
    signal_families: [],
    signal_types: [],
    gameplay_tags: [],
    badges: [],
    signals_json: [],
    top_signals_json: [],
    evidence_json: [],
  },
  {
    promo_id: 'mock-promo-upcoming',
    promo_slug: 'cosmopolitan-upcoming',
    brand: 'Cosmopolitan',
    market_slug: 'las-vegas',
    location_label: 'Las Vegas',
    title: 'Upcoming pool party promo',
    subtitle: 'Starts next month',
    source_kind: 'website',
    source_url: 'https://example.com/cosmo-upcoming',
    primary_asset_url: null,
    active_status: 'upcoming',
    visible_start_date: '2026-04-01',
    visible_end_date: '2026-04-30',
    observed_at: '2026-03-01T08:00:00.000Z',
    signal_families: ['event'],
    signal_types: ['pool_party'],
    gameplay_tags: [],
    badges: [],
    signals_json: [
      {
        signal_id: 'mock-promo-upcoming:v0:0:offer_details.pool_party',
        signal_type: 'pool_party',
        signal_family: 'event',
        label: 'Weekend cabana package',
        value_raw: 'From $199',
        value_normalized: 'From $199',
        confidence: 0.7,
        extraction_key: 'offer_details.pool_party',
      },
    ],
    top_signals_json: [],
    evidence_json: [],
  },
]
